apiVersion: v1
kind: Namespace
metadata:
  name: kube-net-probe
  labels:
    name: kube-net-probe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-net-probe-manager
  namespace: kube-net-probe
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-net-probe-manager
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-net-probe-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-net-probe-manager
subjects:
- kind: ServiceAccount
  name: kube-net-probe-manager
  namespace: kube-net-probe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-net-probe-manager
  namespace: kube-net-probe
  labels:
    app: kube-net-probe-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-net-probe-manager
  template:
    metadata:
      labels:
        app: kube-net-probe-manager
    spec:
      serviceAccountName: kube-net-probe-manager
      containers:
      - name: manager
        image: kube-net-probe-manager:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        - name: api
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: MANAGER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MANAGER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        - --api-server-addr=:9090
        - --leader-elect=true
---
apiVersion: v1
kind: Service
metadata:
  name: kube-net-probe-manager
  namespace: kube-net-probe
  labels:
    app: kube-net-probe-manager
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  - name: api
    port: 9090
    targetPort: api
    protocol: TCP
  selector:
    app: kube-net-probe-manager
